version: '2.3'
services:
  master:
    image: "mysql:5.7"
    container_name: "mysql-master"
    ports:
      - "3307:3306"
    restart: always
    command:
      --innodb_lock_wait_timeout=5
      --sql_mode=""
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_LOG_CONSOLE=true
      - MYSQL_DATABASE=charles
      - TZ=Asia/Shanghai
    volumes:
      - ./data/master:/var/lib/mysql
      - ./conf.d/master:/etc/mysql/mysql.conf.d
  slave1:
    image: "mysql:5.7"
    container_name: "mysql-slave1"
    ports:
      - "3308:3306"
    restart: always
    command:
      --innodb_lock_wait_timeout=5
      --sql_mode=""
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_LOG_CONSOLE=true
      - TZ=Asia/Shanghai
    links:
      - master
    volumes:
      - ./data/slave1:/var/lib/mysql
      - ./conf.d/slave1:/etc/mysql/mysql.conf.d
  slave2:
    image: "mysql:5.7"
    container_name: "mysql-slave2"
    ports:
      - "3309:3306"
    restart: always
    command:
      --innodb_lock_wait_timeout=5
      --sql_mode=""
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_LOG_CONSOLE=true
      - TZ=Asia/Shanghai
    links:
      - master
    volumes:
      - ./data/slave2:/var/lib/mysql
      - ./conf.d/slave2:/etc/mysql/mysql.conf.d
