version: '3.1'
services:
  node-exporter:
    image: prom/node-exporter:v1.0.1
    container_name: "node-exporter"
    ports:
      - "9100:9100"
    restart: always
  zookeeper-exporter:
    image: dabealu/zookeeper-exporter:v0.1.8
    container_name: "zookeeper-exporter"
    command:
      --zk-host=192.168.21.203
      --zk-port=2181
    ports:
      - "9141:9141"
    restart: always
  redis-exporter:
    image: oliver006/redis_exporter:v1.10.0
    container_name: "redis-exporter"
    ports:
      - "9121:9121"
    restart: always
  mongodb-exporter:
    image: ssheehy/mongodb-exporter:0.11.0
    container_name: "mongodb-exporter"
    ports:
      - "9216:9216"
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongodb_exporter:s3cr3tpassw0rd@192.168.21.203:27017
  mysqld-exporter:
    image: prom/mysqld-exporter:v0.12.1
    container_name: "mysqld-exporter"
    command:
      --collect.slave_hosts
      --collect.slave_status
      --collect.binlog_size
      --collect.info_schema.processlist
      --collect.info_schema.innodb_metrics
      --collect.info_schema.innodb_tablespaces
      --collect.info_schema.innodb_cmp
      --collect.info_schema.innodb_cmpmem
    ports:
      - "9104:9104"
    restart: always
    environment:
      - DATA_SOURCE_NAME=exporter:exporter123@(192.168.21.203:3306)/
  # ./prometheus --config.file=prometheus.yml
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: "prometheus"
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      # - ./prometheus/consoles:/prometheus/consoles
      # - ./prometheus/console_libraries:/prometheus/console_libraries
      # - ./prometheus/data/chunks_head:/prometheus/chunks_head
      # - ./prometheus/data/wal:/prometheus/wal
      # - ./prometheus/data/lock:/prometheus/lock
      # - ./prometheus/data/queries.active:/prometheus/queries.active
  # docker run --name mysqld-exporter -d -p 9104:9104 -e DATA_SOURCE_NAME="exporter:123456@(172.31.254.239:3306)/" prom/mysqld-exporter:v0.12.1
  # http://localhost:9090    
  # https://grafana.com/grafana/dashboards/7362
  grafana:
    image: grafana/grafana:7.1.3
    container_name: "grafana"
    ports:
      - "3000:3000"
    restart: always
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - ./grafana/grafana.db:/var/lib/grafana/grafana.db
      - ./grafana/plugins:/var/lib/grafana/plugins
