version: "3"
services:
  web:
    image: hub.c.163.com/mrcharleshu/python-counter-web:v2
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:5000"
    networks:
      - webnet
networks:
  webnet:
