version: '3'
services:
  web:
    build: .
    #image: docker-compose_web:latest
    ports:
      - "5000:5000"
    volumes:
      - .:/code
  redis:
    image: "redis:alpine"
    # Not requried
    ports:
      - "6379:6379"
