version: '3'
services:
  redis:
    image: "redis:latest"
    container_name: "local-redis"
    ports:
      - "6379:6379"
    restart: always
  mysql:
    image: "mysql:5.7"
    container_name: "local-mysql"
    ports:
      - "3306:3306"
    restart: always
    command:
      --innodb_lock_wait_timeout=5
      --sql_mode=""
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_LOG_CONSOLE=true # which is its default state for MySQL 8.0 server containers
      - MYSQL_DATABASE=plant_insight
      - TZ=Asia/Shanghai
    volumes:
    - /private/var/docker_data/mysql/data/:/private/var/lib/mysql
  adminer:
    image: adminer
    container_name: "local-adminer"
    restart: always
    ports:
      - 3308:8080
