version: '3.1'
services:
  redis:
    image: "bitnami/redis:5.0.3"
    container_name: "local-redis"
    ports:
      - "6379:6379"
    restart: always
    environment:
      - REDIS_PASSWORD=123
    volumes:
      - redis_storage:/opt/bitnami/redis/etc
  mysql:
    image: "mysql:5.7"
    container_name: "local-mysql"
    ports:
      - "3306:3306"
    restart: always
    command:
      --innodb_lock_wait_timeout=5
      --sql_mode=""
    environment:
      # - ALLOW_EMPTY_PASSWORD=yes
      # - MONGODB_PRIMARY_ROOT_USER=root
      # - MONGODB_PRIMARY_ROOT_PASSWORD=123
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_LOG_CONSOLE=true # which is its default state for MySQL 8.0 server containers
      - MYSQL_DATABASE=plant_insight
      - TZ=Asia/Shanghai
    volumes:
    - mysql_storage:/var/lib/mysql
  adminer:
    image: adminer
    container_name: "local-adminer"
    restart: always
    ports:
      - 3308:8080
  fix-mongodb-permissions:
    image: 'bitnami/mongodb:4.0'
    container_name: "local-mongodb-permission-fix"
    user: root
    command: chown -R 1001:1001 /opt/bitnami/mongodb && chown -R 1001:1001 /bitnami/mongodb/data
    volumes:
      - mongodb_storage_1:/opt/bitnami/mongodb
      - mongodb_storage_2:/bitnami/mongodb/data
  mongodb:
    image: 'bitnami/mongodb:4.0'
    container_name: "local-mongodb"
    ports:
      - "27017:27017"
    environment:
      # - ALLOW_EMPTY_PASSWORD=yes
      # - MONGODB_PRIMARY_ROOT_USER=root
      # - MONGODB_PRIMARY_ROOT_PASSWORD=123
      - MONGODB_ROOT_PASSWORD=hDxK6o_7dF_YLkuUZ
      - MONGODB_USERNAME=milu
      - MONGODB_PASSWORD=KuJ9i_of3hU_dGz3d
      - MONGODB_DATABASE=mintmuse
    volumes:
      - mongodb_storage_1:/opt/bitnami/mongodb
      - mongodb_storage_2:/bitnami/mongodb/data
    depends_on:
      - fix-mongodb-permissions
volumes:
  redis_storage:
  mysql_storage:
  mongodb_storage_1:
  mongodb_storage_2:

